import fs from 'fs/promises';
import path from 'path';

/**
 * Servizio per rigenerare i file TypeScript projects.ts e imageMeta.ts
 */
export class FileGenerator {
  constructor(publicPath, srcPath) {
    this.publicPath = publicPath;
    this.srcPath = srcPath;
  }

  /**
   * Rigenera src/shared/data/projects.ts basandosi su projects.json
   */
  async regenerateProjectsFile(projectsData) {
    const projectsArray = projectsData.map(project => {
      // Nuovi progetti usano /cover/, progetti vecchi usano /1/
      const coverPath = project.hasCover ? 'cover' : '1';
      
      return `  {
    slug: '${project.slug}',
    title: '${project.title.replace(/'/g, "\\'")}',
    dateISO: '${project.dateISO}',
    description: '${project.description.replace(/'/g, "\\'")}',
    cover: {
      id: '${project.slug}-cover',
      src: '/optimized/${project.slug}/${coverPath}/thumb.webp',
      originalUrl: '/optimized/${project.slug}/${coverPath}/original.jpg',
      alt: '${project.title.replace(/'/g, "\\'")}',
    },
    gallery: createProjectPhotos('${project.slug}', ${project.imageCount}),
  }`;
    }).join(',\n');

    const fileContent = `import type { Project, Photo } from '../../shared/types'

// Genera le foto per ogni progetto basandosi sulle cartelle in public/assets
const createProjectPhotos = (projectSlug: string, count: number): Photo[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: \`\${projectSlug}-\${i + 1}\`,
    src: \`/optimized/\${projectSlug}/\${i + 1}/thumb.webp\`,
    originalUrl: \`/optimized/\${projectSlug}/\${i + 1}/original.jpg\`,
    alt: \`Foto \${i + 1} del progetto \${projectSlug}\`,
  }))
}

export const projects: Project[] = [
${projectsArray}
]
`;

    const outputPath = path.join(this.srcPath, 'shared', 'data', 'projects.ts');
    await fs.writeFile(outputPath, fileContent);
    
    return outputPath;
  }

  /**
   * Rigenera src/shared/data/imageMeta.ts scansionando le cartelle optimized
   */
  async regenerateImageMetaFile() {
    const optimizedPath = path.join(this.publicPath, 'optimized');
    const metaEntries = [];

    try {
      const projects = await fs.readdir(optimizedPath);
      
      for (const projectSlug of projects) {
        const projectPath = path.join(optimizedPath, projectSlug);
        const stat = await fs.stat(projectPath);
        
        if (!stat.isDirectory()) continue;

        const images = await fs.readdir(projectPath);
        
        for (const imageIndex of images) {
          const imagePath = path.join(projectPath, imageIndex);
          const imageStat = await fs.stat(imagePath);
          
          if (!imageStat.isDirectory()) continue;

          // Leggi meta.json
          const metaPath = path.join(imagePath, 'meta.json');
          try {
            const metaContent = await fs.readFile(metaPath, 'utf-8');
            const meta = JSON.parse(metaContent);
            
            const thumbPath = `/optimized/${projectSlug}/${imageIndex}/thumb.webp`;
            metaEntries.push({
              path: thumbPath,
              ratio: meta.ratio,
              placeholder: meta.placeholder
            });
          } catch (err) {
            console.warn(`Impossibile leggere meta.json per ${projectSlug}/${imageIndex}`);
          }
        }
      }

      // Ordina per path
      metaEntries.sort((a, b) => a.path.localeCompare(b.path));

      // Genera il contenuto del file
      const entries = metaEntries.map(entry => 
        `  "${entry.path}": { ratio: ${entry.ratio.toFixed(6)}, placeholder: "${entry.placeholder}" }`
      ).join(',\n');

      const fileContent = `// AUTO-GENERATED by backend CMS
export const imageMeta: Record<string, { ratio: number; placeholder: string }> = {
${entries}
};
`;

      const outputPath = path.join(this.srcPath, 'shared', 'data', 'imageMeta.ts');
      await fs.writeFile(outputPath, fileContent);
      
      return outputPath;
    } catch (error) {
      console.error('Errore durante la rigenerazione di imageMeta.ts:', error);
      throw error;
    }
  }

  /**
   * Legge il file projects.json
   */
  async readProjectsData(dataPath) {
    try {
      const content = await fs.readFile(dataPath, 'utf-8');
      return JSON.parse(content);
    } catch (error) {
      // Se il file non esiste, ritorna array vuoto
      if (error.code === 'ENOENT') {
        return [];
      }
      throw error;
    }
  }

  /**
   * Salva il file projects.json
   */
  async saveProjectsData(dataPath, projectsData) {
    await fs.mkdir(path.dirname(dataPath), { recursive: true });
    await fs.writeFile(dataPath, JSON.stringify(projectsData, null, 2));
  }
}

