version: '3.8'

services:
  # Frontend React - sito-rafa
  sito-rafa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sito-rafa
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - frontend_build:/app/dist
    networks:
      - web-proxy

volumes:
  frontend_build:
    driver: local

networks:
  web-proxy:
    external: true


