version: '3.8'

services:
  # Frontend React - I Gladiatori Landing Page
  igladiatori-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igladiatori_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - frontend_build:/app/dist
    networks:
      - web-proxy

volumes:
  frontend_build:
    driver: local

networks:
  web-proxy:
    external: true


