version: '3.8'

services:
  sito-rafa:
    image: 192.168.0.23:5000/sito-rafa:latest
    container_name: sito-rafa
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - web-proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web-proxy:
    external: true